---
# NCNR Specific Tasks

- name: "NCNR | Create tenscan user"
  user:
      name: tenscan
      groups: wheel
      state: present
  when: ncnrcis_install_tenscan
  tags: 
    - level1
    - tenscan
    - patch
    - ncnr

- name: Set tenscan user RSA key
  authorized_key:
      user: tenscan
      key: http://network.ncnr.nist.gov/tenscan_rsa.pub
      state: present
  when: ncnrcis_install_tenscan
  tags: 
    - level1
    - tenscan
    - patch
    - ncnr

- name: "NCNR | Set files to 644 so tenable can read it"
  file:
      dest: "{{ item }}"
      state: file
      owner: root
      group: root
      mode: 0644
  with_items:
      - /etc/modprobe.d/CIS.conf
      - /etc/audit/auditd.conf
  tags:
      - level1
      - patch
      - ncnr

- name: "NCNR | Ensure BigFix is installed"
  command: rpm -q BESAgent
  register: bes_check    
  ignore_errors: yes
  tags:
      - level1
      - bigfix
      - patch
      - ncnr

- name: "NCNR | Copy bigfix install file if x86_64"
  copy:
      src: /home/ncnradmin/linuxinstall/bigfix-rhe5.x86_64.tar
      dest: /tmp/bigfix.tar
      owner: root
      group: root
      mode: 0644
  when: (ansible_architecture == "x86_64" and bes_check.rc == 1) and ncnrcis_install_bigfix
  tags:
      - level1
      - bigfix
      - patch
      - ncnr

- name: "NCNR | Copy bigfix install file if i386"
  copy:
      src: /home/ncnradmin/linuxinstall/bigfix-rhe5.i686.tar
      dest: /tmp/bigfix.tar
      owner: root
      group: root
      mode: 0644
  when: (ansible_architecture == "i386" and bes_check.rc == 1) and ncnrcis_install_bigfix
  tags:
      - level1
      - bigfix
      - patch
      - ncnr

- name: "NCNR | Untar bigfix"
  command: tar xvf /tmp/bigfix.tar
  args:   
      chdir: /tmp/
  when: (bes_check.rc == 1 and ncnrcis_install_bigfix)
  tags:
      - level1
      - bigfix
      - patch
      - ncnr

- name: "NCNR | Runs bigfix install script"
  command: /tmp/bigfix/NIST_Installation_Script.sh
  args:   
      chdir: /tmp/bigfix/
  when: (bes_check.rc == 1 and ncnrcis_install_bigfix)
  tags:
      - level1
      - bigfix
      - patch
      - ncnr

- name: "NCNR | Delete bigfix install files"
  command: rm -rf /tmp/bigfix /tmp/bigfix.tar
  when: (bes_check.rc == 1 and ncnrcis_install_bigfix)
  tags:
      - level1
      - bigfix
      - patch
      - ncnr

- name: "NCNR | Ensure BigFix is running"
  service:
      name: besclient
      state: started
      enabled: yes
  tags:
      - level1
      - bigfix
      - patch
      - ncnr
